# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.2
      with:
        version: 12
    - name: GitHib Action for yarn
      uses: Borales/actions-yarn@v.3.0
      with:
        # yarn command
        cmd: install
        
    - name: creating build
      run: yarn build
    - name: Installing surge
      run: npm install -g surge
      
    - name: deploying on surge
      run: surge ./build http://appreact_2020.surge.sh/ --token ${{secrets.SURGE_TOKEN}}
    
       
